# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- bash: |
    echo Update GitHub repo
    git config user.email "chaltinpagan@gmail.com"
    git config user.name "Chaltin Pagan"
    git add .
    git commit -m 'fetching latest changes from azure devops repo'
    git push https://chaltinpagan:$(GithubPAT)@github.com/ChaltinPagan/RazorPagesADO.git main
  displayName: 'Updating GitHub repo'
